### ISSUE TITLE
For Laravel 5.8 support

### ISSUE THREAD

**Issue by samiref** [mpociot/laravel-couchbase#44]
### for laravel 5.8 support 
*****
**in Mpociot\Couchbase\Eloquent\Model.php**  

> Line 151 

convert 
`protected function getDateFormat()`
to
`public function getDateFormat()`

*****
 **in Mpociot\Couchbase\Eloquent\HybridRelations.php** 
> Line 173

change
`public function morphTo($name = null, $type = null, $id = null)`
to 
`public function morphTo($name = null, $type = null, $id = null, $ownerKey = NULL)`

> Line 219

change 
`public function belongsToMany($related, $collection = null, $foreignKey = null, $otherKey = null, $relation = null)`
to
`public function belongsToMany($related, $collection = null, $foreignKey = null, $otherKey = null, $parentKey = NULL, $relatedKey = NULL, $relation = null)`

> Line 230

change
`return parent::belongsToMany($related, $collection, $foreignKey, $otherKey, $relation);`
to 
`return parent::belongsToMany($related, $collection, $foreignKey, $otherKey, $parentKey, $relatedKey, $relation);`

**Comment by samiref** [comment]
i can't send pull request this repository because **github has sanction iranians developers**.

@pedmindset please edit code.

Thanks.

**Comment by sgc-fireball** [comment]
done PR46
