### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by kamal250** [mpociot/laravel-couchbase#9]
I am getting following error when try to migrate:

` [ErrorException]                                                       
  Couchbase\Cluster::__construct() expects exactly 1 parameter, 3 given  
                                                                         

Exception trace:
 () at /vagrant/vendor/mpociot/couchbase/src/Mpociot/Couchbase/Connection.php:268
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 Couchbase\Cluster->__construct() at /vagrant/vendor/mpociot/couchbase/src/Mpociot/Couchbase/Connection.php:268
 Mpociot\Couchbase\Connection->createConnection() at /vagrant/vendor/mpociot/couchbase/src/Mpociot/Couchbase/Connection.php:47
 Mpociot\Couchbase\Connection->__construct() at /vagrant/vendor/mpociot/couchbase/src/Mpociot/Couchbase/CouchbaseServiceProvider.php:26
 Mpociot\Couchbase\CouchbaseServiceProvider->Mpociot\Couchbase\{closure}() at n/a:n/a
 call_user_func() at /vagrant/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:106
 Illuminate\Database\DatabaseManager->makeConnection() at /vagrant/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:71
 Illuminate\Database\DatabaseManager->connection() at /vagrant/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:184
 Illuminate\Database\Migrations\DatabaseMigrationRepository->getConnection() at /vagrant/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:152
 Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists() at /vagrant/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:538
 Illuminate\Database\Migrations\Migrator->repositoryExists() at /vagrant/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:96
 Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase() at /vagrant/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:62
 Illuminate\Database\Console\Migrations\MigrateCommand->fire() at n/a:n/a
 call_user_func_array() at /vagrant/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /vagrant/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /vagrant/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:531
 Illuminate\Container\Container->call() at /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /vagrant/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /vagrant/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /vagrant/vendor/symfony/console/Application.php:200
 Symfony\Component\Console\Application->doRun() at /vagrant/vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /vagrant/artisan:35`

Additional information:
1. Fresh installation of Laravel 5.4
2. PHP SDK installed along with Couchbase Enterprise Edition
3. Executed php artisan make:auth and then executing php artisan migrate -vvv
4. No Lumen used so added only service provider in config/app.php

**Comment by dcarbone** [comment]
You are probably using version 3 of the pecl extension.  This lib currently only supports version 2.

**Comment by seanramey82** [comment]
Version 3? It appears that PECL only goes up to version 2.4.0. Which version are you talking about? 

Thanks!

**Comment by dcarbone** [comment]
Yes, sorry, they changed quite a bit between version 2.2 and 2.3.

iirc, this works with any version from 2016, up to 2.2.4.

**Comment by spresnac** [comment]
@kamal250 we fixed that just now ;)
